package ru.neexol.debtable.utils.exceptions

class UserAlreadyInvitedException : Exception()